version: "1.0"
services:
  streamlit:
    container_name: streamlit_app
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
  mysql:
    container_name: db
    image: mysql
    ports:
      - "8501:8501"
    environment:
        MYSQL_ROOT_PASSWORD: 12345678rk
  app:
    container_name: app
    links:
      - "mysql"
      - "streamlit"
    build: .
    ports:
      - "8501:8501"
